#!/usr/bin/env bash
# inproxy interactive installer. Run as root:  sudo ./deploy/install.sh [./inproxy]
set -euo pipefail

BINARY_SRC="${1:-./inproxy}"
BIN_DST="/usr/local/bin/inproxy"
ETC_DIR="/etc/inproxy"
ENV_FILE="$ETC_DIR/inproxy.env"
UNIT="/etc/systemd/system/inproxy.service"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ $EUID -ne 0 ]]; then echo "Please run as root: sudo $0" >&2; exit 1; fi
if [[ ! -f "$BINARY_SRC" ]]; then
  echo "Binary $BINARY_SRC not found. Build it first: CGO_ENABLED=0 go build -o inproxy ." >&2
  exit 1
fi

echo "================ inproxy installer ================"

# ---- 1. Pick internal / external interfaces ----
mapfile -t ADDRS < <(ip -o -4 addr show scope global 2>/dev/null | awk '{print $2"\t"$4}')
if [[ ${#ADDRS[@]} -eq 0 ]]; then
  echo "No network interfaces detected; please enter values manually."
fi
echo
echo "Detected interfaces (iface  IP/mask):"
for i in "${!ADDRS[@]}"; do printf "  [%d] %s\n" "$i" "${ADDRS[$i]}"; done
echo "  [m] enter manually"
echo

pick_ip() {  # $1=prompt ; sets globals PICK_IP / PICK_CIDR
  local prompt="$1" choice
  read -rp "$prompt" choice
  if [[ "$choice" == "m" || -z "${ADDRS[*]:-}" ]]; then
    read -rp "  Enter IP/mask (e.g. 10.8.0.5/24): " PICK_CIDR
  else
    PICK_CIDR=$(awk '{print $2}' <<<"${ADDRS[$choice]}")
  fi
  PICK_IP=${PICK_CIDR%/*}
}

pick_ip "Select the INTERNAL interface number (admin UI binds here): " ; INTERNAL_IP=$PICK_IP ; INTERNAL_CIDR_DET=$PICK_CIDR
pick_ip "Select the EXTERNAL interface number (serves public HTTPS): " ; EXTERNAL_IP=$PICK_IP

# ---- 2. External domain (for Let's Encrypt) ----
echo
read -rp "External domain (for HTTPS cert; leave empty to use a self-signed cert for ${EXTERNAL_IP}): " EXTERNAL_HOST
if [[ -n "$EXTERNAL_HOST" ]]; then
  TLS_MODE=auto
  read -rp "ACME notification email (optional, press enter to skip): " ACME_EMAIL
else
  TLS_MODE=self
  EXTERNAL_HOST=$EXTERNAL_IP
  ACME_EMAIL=""
fi

# ---- 3. Admin UI port ----
echo
read -rp "Admin UI port [8443]: " ADMIN_PORT ; ADMIN_PORT=${ADMIN_PORT:-8443}

# ---- 4. Admin password ----
EXIST_PW=""
[[ -f "$ENV_FILE" ]] && EXIST_PW=$(grep -E '^ADMIN_PASSWORD=' "$ENV_FILE" | head -1 | cut -d= -f2- || true)
echo
if [[ -n "$EXIST_PW" && "$EXIST_PW" != "change-me-please" ]]; then
  read -rp "An admin password already exists. Keep it? [Y/n]: " keep
  [[ "${keep,,}" == "n" ]] && read -rsp "  New admin password: " ADMIN_PASSWORD && echo || ADMIN_PASSWORD=$EXIST_PW
else
  read -rsp "Set the admin UI login password: " ADMIN_PASSWORD ; echo
fi
[[ -z "$ADMIN_PASSWORD" ]] && ADMIN_PASSWORD="change-me-please"

INTERNAL_CIDR="${INTERNAL_CIDR_DET},127.0.0.1/32,::1/128"

# ---- Write files ----
echo
echo "==> Creating system user 'inproxy'"
id -u inproxy &>/dev/null || useradd --system --no-create-home --shell /usr/sbin/nologin inproxy

echo "==> Installing binary to $BIN_DST"
install -m 0755 "$BINARY_SRC" "$BIN_DST"
setcap 'cap_net_bind_service=+ep' "$BIN_DST" 2>/dev/null || true

echo "==> Writing config to $ETC_DIR"
mkdir -p "$ETC_DIR" "$ETC_DIR/tls" "$ETC_DIR/acme"
[[ -f "$ETC_DIR/config.json" ]] || echo "[]" > "$ETC_DIR/config.json"

cat > "$ENV_FILE" <<EOF
# Generated by install.sh; after editing run: sudo systemctl restart inproxy
ADMIN_PASSWORD=${ADMIN_PASSWORD}

# External HTTPS proxy (all interfaces; internal users may use it too)
PROXY_ADDR=:443
HTTP_REDIRECT_ADDR=:80

# Certificate: auto=Let's Encrypt (needs domain -> external IP) / self=self-signed / file=your own
TLS_MODE=${TLS_MODE}
EXTERNAL_HOST=${EXTERNAL_HOST}
ACME_EMAIL=${ACME_EMAIL}
ACME_CACHE=${ETC_DIR}/acme
TLS_CERT=${ETC_DIR}/tls/cert.pem
TLS_KEY=${ETC_DIR}/tls/key.pem

# Admin UI: dedicated port bound to the internal IP, reachable only from INTERNAL_CIDR
ADMIN_ADDR=${INTERNAL_IP}:${ADMIN_PORT}
ADMIN_TLS=false
INTERNAL_CIDR=${INTERNAL_CIDR}

CONFIG_PATH=${ETC_DIR}/config.json
EOF

chown -R inproxy:inproxy "$ETC_DIR"
chmod 640 "$ENV_FILE"

echo "==> Installing systemd unit"
cp "$HERE/inproxy.service" "$UNIT"
systemctl daemon-reload
systemctl enable inproxy >/dev/null 2>&1 || true

cat <<EOF

Done. Config written to $ENV_FILE

  Public service:  https://${EXTERNAL_HOST}/<prefix>/...   (TLS_MODE=${TLS_MODE})
  Admin UI:        http://${INTERNAL_IP}:${ADMIN_PORT}/_admin   (only ${INTERNAL_CIDR_DET})

Start:        sudo systemctl start inproxy
View logs:    journalctl -u inproxy -f
EOF
if [[ "$TLS_MODE" == "auto" ]]; then
  echo
  echo "Note: Let's Encrypt requires ${EXTERNAL_HOST} to resolve to ${EXTERNAL_IP}, with ports 80/443 reachable from the internet."
fi
